project_id = "ncetgnojwfrnsxpytcia"

[functions.send-confirmation-email]
verify_jwt = false

[functions.catalog-import]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.verify-subscription]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.paystack-subscription-webhook]
verify_jwt = false

[functions.maps-distance]
verify_jwt = false
