project_id = "ncetgnojwfrnsxpytcia"

[functions.send-confirmation-email]
verify_jwt = false

[functions.catalog-import]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.verify-subscription]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.paystack-subscription-webhook]
verify_jwt = false

[functions.maps-distance]
verify_jwt = false

[functions.whoami]
verify_jwt = false

[functions.rider-session]
verify_jwt = false

[functions.rider-nearest-assignment]
verify_jwt = false

[functions.rider-update-status]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false
