[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    cache-control = "max-age=31536000"
    

