// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncetgnojwfrnsxpytcia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZXRnbm9qd2ZybnN4cHl0Y2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzE0NTUsImV4cCI6MjA2NzMwNzQ1NX0.iqpQuWl2OThOYW2c7lefPOD9bMmU6YutE9HWEewuMw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});